{% set python_min = "3.10" %}
{% set name = "drms" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4be944448db107b55dd0de3045d326906edd13fa7c31ef0d091ae96fcc7de5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - packaging

test:
  requires:
    - setuptools
    - pip
    - pytest-astropy
    - python {{ python_min }}
  imports:
    - drms
  commands:
    - python -c "from pkg_resources import get_distribution; print(get_distribution('drms'))"
    - python -c "from importlib.metadata import version; print(version('drms'))"
    - pytest --pyargs drms --remote-data=none

about:
  home: https://github.com/sunpy/drms
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Access HMI, AIA and MDI data with Python
  description: |
    The ``drms`` module provides an easy-to-use interface for accessing HMI, AIA and MDI data with Python.
    It uses the publicly accessible `JSOC <http://jsoc.stanford.edu/>`_ DRMS server by default, but can also\nbe used with local `NetDRMS <http://jsoc.stanford.edu/netdrms/>`_ sites.
    More information, including a detailed tutorial is available on `Read the Docs <http://docs.sunpy.org/projects/drms/>`_.
  doc_url: http://docs.sunpy.org/projects/drms/
  dev_url: https://github.com/sunpy/drms

extra:
  recipe-maintainers:
    - wtbarnes
    - Cadair
    - nabobalis
