{% set name = "drms" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0475a8ca3618c5b970e48dc00ea5d353301d9ed2d4dbcba4fd0bf7666d1aac6a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm
  run:
    - {{ pin_compatible('numpy') }}
    - pandas
    - python >=3.9
    - packaging

test:
  requires:
    - setuptools
  imports:
    - drms
  commands:
    - python -c "from pkg_resources import get_distribution; print(get_distribution('drms'))"
    - python -c "from importlib.metadata import version; print(version('drms'))"

about:
  home: https://github.com/sunpy/drms
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Access HMI, AIA and MDI data with Python
  description: |
    The ``drms`` module provides an easy-to-use interface for accessing HMI, AIA and MDI data with Python.
    It uses the publicly accessible `JSOC <http://jsoc.stanford.edu/>`_ DRMS server by default, but can also\nbe used with local `NetDRMS <http://jsoc.stanford.edu/netdrms/>`_ sites.
    More information, including a detailed tutorial is available on `Read the Docs <http://docs.sunpy.org/projects/drms/>`_.
  doc_url: http://docs.sunpy.org/projects/drms/
  dev_url: https://github.com/sunpy/drms

extra:
  recipe-maintainers:
    - wtbarnes
    - Cadair
    - nabobalis
