travis:
  secure:
    BINSTAR_TOKEN: GYNcfnR/Ad9UG96nEpciydC3U6ZCCcmOmCzhwQUkk73qjNdrfRGWvLGclDFROkdI+M2gGjO1h5LAB+ITfCHj4HFq6T7btpo/GtqWtoUMzAiLq/YGkM7pn/bI+zone9vK1+RTZwgZvGiVXO3ie856NoMtYBkGpUE/ZqOI7D+XpaVMU5yOqMLeJwzw8a07mz4+qH8gnTDAC1tNOZK/F9S19kfKq8ZGHzObuVaHxTokjnY3Bg94p2Movo6fcbIzq7+OvkatK9hMy7Lh2VGDVX0zMrdYmo8Q5is5fIoNhjweYJnv0YQ1E7qkiopB4GLkUisDFUQgP2ZOx0NnzC/LDEjkYs02ohKG5Zcvkp7RataSHXSwTcPC9nl0uTJciiNHdFYOkG4hOC0JspO45syo1etGRgHx0oZuIHtLMkVcgemaq+FOVQ44GrSeEGF5+tz5Ao87o3H9jHHVor6x7zRbK2U4Fboe9okjakSh7enqI0wX6QmU87J/nH9AUSB9QkAxj13SmDDJLjBDxK6oNo28ZyYFIMjD/TKD/12iNHxtk2K3JVVxia7/+Vj9VoI9bJCCace6ZXObKIzD1zugQvD5whcPoq3e2HLbAMVB2QEX691X5ajSBrma7D27YZK+WM8YRqIpqgjGY4lCuOLiC380Ou6FazcYNthY2P02zfQsIxivUzY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
